### ISSUE TITLE
[Conflict] with Levelloader

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#88]
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::LoadShipGrabbableItems>(StartOfRound)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Start>(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?1784313794(StartOfRound)
LethalLib.Modules.Items.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <c68aa40cbbae4bd69cd2fcd50c8f1ae1>:IL_0178)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-700862764(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-2070820660(StartOfRound)
LethalLib.Modules.Utilities.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <c68aa40cbbae4bd69cd2fcd50c8f1ae1>:IL_019C)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-917453156(StartOfRound)

[Info   : Unity Log] Parsed word: gei
[Info   : Unity Log] noun keyword: geiger-counter ; verb keyword: buy ; result null? : False
[Info   : Unity Log] result: Geiger-counterBuyNode1
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
Terminal.LoadNewNodeIfAffordable (TerminalNode node) (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_006D)
Terminal.OnSubmit () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_00CB)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent\`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction\`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by CoolLKKPS** [comment]
and im sure only this mod can cause that issue

**Comment by CoolLKKPS** [comment]
to reproduce:
1. install this modpack
2. install LittleCompany
3. create a lobby and quit to main menu
4. re-create a lobby and try to order "geiger" mod items

and the dropship won't give u geiger instead to give u another

**Comment by CoolLKKPS** [comment]
[Dark Hour v50 - 240523_1716454823086.zip](https://github.com/MehimoNemo/LethalCompanyShrinkRay/files/15414506/Dark.Hour.v50.-.240523_1716454823086.zip)

**Comment by CoolLKKPS** [comment]
@NiroDev

**Comment by CoolLKKPS** [comment]
and use this modpack to test #83

**Comment by CoolLKKPS** [comment]
and #87 in poolroom dungeon

**Comment by CoolLKKPS** [comment]
#87 additional: no matter the player size btw, just use normal size

**Comment by CoolLKKPS** [comment]
god i hope, those issues will get fix asap, i super don't like those issues

**Comment by CoolLKKPS** [comment]
Confirmed old issue

**Comment by CoolLKKPS** [comment]
modlist:
1. levelloader (conflict)
2. littlecompany
3. meltdown

**Comment by CoolLKKPS** [comment]
@NiroDev u really have to fix this asap, just create the lobby twice, i already spend many time to test that

**Comment by NiroDev** [comment]
Tested with
LethalLevelLoader
LittleCompany
FacilityMeltdown

Started a round, spawned shrinkray, bought geiger from store, brought both back to ship, left planet, autosaved, restarted lobby -> worked. restarted game and lobby -> worked too.

Am i maybe missing something, wrong routine, or wrong mods?

**Comment by NiroDev** [comment]
I will test this in detail tomorrow and see if I can do something from our side, even though LittleCompany isn't throwing any errors in this case

**Comment by AboveFire** [comment]
Yeah so the problem is most likely with LethalLevelLoader. It doesn't handle items well right now, and I did a thing where if LethalLevelLoader is there then we use it to register items instead of LethalLib which everybody else uses.

Just post a fix so that we always default to LethalLib, but added a config so that we can switch to LethalLevelLoader for testing purposes.

Since LethalLib is compatible with lethalLevelLoader, you shopuldnt have this issue anymore.

**Comment by CoolLKKPS** [comment]
tbh, other mods doesn't have this issues, and in previous version of LittleCompany this issue will still present, so i don't believe there's no problem at all, in fact this issue already about a month i think, but i cannot find what happen until i disable this mod

**Comment by AboveFire** [comment]
Yes, no other mods use LethalLevelLoader to register items except for GiantSpecimens which reverted to using LethalLib because it was having issues. I tought we were fine but apparently not. So that's why I pushed a change to go back to using LethalLib

**Comment by CoolLKKPS** [comment]
And remember, buy mod item **After** re-create a lobby

**Comment by CoolLKKPS** [comment]
uh can u push a new release with this [commit](https://github.com/MehimoNemo/LethalCompanyShrinkRay/commit/ef7e8b09817394619b79743e15af95858973bdd7) so i can update my modpack? that will really good for us bc i going to release new version of my modpack to let my party member to test there's any other issues still exist
and btw i agree register items method can compatible with LLL (If its stable); tbh from beta version to release version, i am happy LittleCompany are getting more stable now, so i have to say, don't forget to take a break, even i update my modpack almost everyday

**Comment by NiroDev** [comment]
Fixed in 1.0.10, which was just released

I'm glad that we got this mod mostly stable by now too, considering the amount of features it has. What i like the most is that as long as you don't change any player/item/enemy sizes it feels like vanilla gameplay because not much is changing.

**Comment by CoolLKKPS** [comment]
yippe!
